17th July, 2026

Upload the cleaned dataset

In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\jayal\leaned_online_retail.csv")

In [3]:
df[['InvoiceMonth','CohortMonth']].dtypes

InvoiceMonth    object
CohortMonth     object
dtype: object

In [4]:
df['InvoiceMonth'] = pd.to_datetime(df['InvoiceMonth']).dt.to_period('M')
df['CohortMonth'] = pd.to_datetime(df['CohortMonth']).dt.to_period('M')

In [5]:
df[['InvoiceMonth','CohortMonth']].dtypes

InvoiceMonth    period[M]
CohortMonth     period[M]
dtype: object

In [6]:
#Cohort Index
df['CohortIndex'] = (df['InvoiceMonth'] - df['CohortMonth']).apply(lambda x: x.n)

In [8]:
df[['CustomerID','InvoiceMonth','CohortMonth','CohortIndex']].head(20)

    CustomerID InvoiceMonth CohortMonth  CohortIndex
0      17850.0      2010-12     2010-12            0
1      17850.0      2010-12     2010-12            0
2      17850.0      2010-12     2010-12            0
3      17850.0      2010-12     2010-12            0
4      17850.0      2010-12     2010-12            0
5      17850.0      2010-12     2010-12            0
6      17850.0      2010-12     2010-12            0
7      17850.0      2010-12     2010-12            0
8      17850.0      2010-12     2010-12            0
9      13047.0      2010-12     2010-12            0
10     13047.0      2010-12     2010-12            0
11     13047.0      2010-12     2010-12            0
12     13047.0      2010-12     2010-12            0
13     13047.0      2010-12     2010-12            0
14     13047.0      2010-12     2010-12            0
15     13047.0      2010-12     2010-12            0
16     13047.0      2010-12     2010-12            0
17     13047.0      2010-12     2010-12            0
18     13047.0      2010-12     2010-12            0
19     13047.0      2010-12     2010-12            0

In [10]:
df[df['CustomerID'] == 13047][['CustomerID','InvoiceMonth','CohortMonth','CohortIndex']]

        CustomerID InvoiceMonth CohortMonth  CohortIndex
9          13047.0      2010-12     2010-12            0
10         13047.0      2010-12     2010-12            0
11         13047.0      2010-12     2010-12            0
12         13047.0      2010-12     2010-12            0
13         13047.0      2010-12     2010-12            0
...            ...          ...         ...          ...
284895     13047.0      2011-10     2010-12           10
284896     13047.0      2011-10     2010-12           10
284897     13047.0      2011-10     2010-12           10
284898     13047.0      2011-10     2010-12           10
326021     13047.0      2011-11     2010-12           11

[172 rows x 4 columns]