11th July, 2026

In [21]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as py
import seaborn as sns

In [22]:
#Load Dataset
df = pd.read_csv(r"C:\Users\jayal\Desktop\online_retail.csv")

In [23]:

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom

In [24]:
df.shape

(541909, 8)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [26]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

12th July,2026

In [27]:
#Handle missing CustomerID
df = df.dropna(subset=['CustomerID'])
df.shape

(406829, 8)

In [28]:
#Investigate negative Quantity
df[df['Quantity']<0]['InvoiceNo'].head(10)

141    C536379
154    C536383
235    C536391
236    C536391
237    C536391
238    C536391
239    C536391
240    C536391
241    C536391
939    C536506
Name: InvoiceNo, dtype: object

13th July 2026

In [29]:
#Filter out cancelled transactions
df = df[~df['InvoiceNo'].str.startswith('C')]

In [30]:
df.shape

(397924, 8)

In [31]:
df['Quantity'].describe()

count    397924.000000
mean         13.021823
std         180.420210
min           1.000000
25%           2.000000
50%           6.000000
75%          12.000000
max       80995.000000
Name: Quantity, dtype: float64

14th July, 2026

In [32]:
#Convert InvoiceDate to proper datetime format
df['InvoiceDate'].dtype

dtype('O')

In [33]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'],dayfirst=True)

In [34]:
df['InvoiceDate'].dtype

dtype('<M8[ns]')

In [35]:
df['InvoiceDate'].head()

0   2010-12-01 08:26:00
1   2010-12-01 08:26:00
2   2010-12-01 08:26:00
3   2010-12-01 08:26:00
4   2010-12-01 08:26:00
Name: InvoiceDate, dtype: datetime64[ns]

In [36]:
#Find and Remove duplicates
df.duplicated().sum()

np.int64(5192)

In [37]:
print("Before removing duplicates:",df.shape)
df = df.drop_duplicates()
print("After removing duplicates:",df.shape)

Before removing duplicates: (397924, 8)
After removing duplicates: (392732, 8)

15th July, 2026

In [18]:
#Find cohort month

In [44]:
#Extract year-month
df['InvoiceMonth'] = df['InvoiceDate'].dt.to_period('M')

In [45]:
df['InvoiceMonth'].head()

0    2010-12
1    2010-12
2    2010-12
3    2010-12
4    2010-12
Name: InvoiceMonth, dtype: period[M]

In [40]:
df['InvoiceDate'].head()

0   2010-12-01 08:26:00
1   2010-12-01 08:26:00
2   2010-12-01 08:26:00
3   2010-12-01 08:26:00
4   2010-12-01 08:26:00
Name: InvoiceDate, dtype: datetime64[ns]

In [41]:
df['CohortMonth'] = df.groupby('CustomerID')['InvoiceMonth'].transform('min')

In [42]:
df[['CustomerID','InvoiceMonth','CohortMonth']].head(10)

   CustomerID InvoiceMonth CohortMonth
0     17850.0      2010-12     2010-12
1     17850.0      2010-12     2010-12
2     17850.0      2010-12     2010-12
3     17850.0      2010-12     2010-12
4     17850.0      2010-12     2010-12
5     17850.0      2010-12     2010-12
6     17850.0      2010-12     2010-12
7     17850.0      2010-12     2010-12
8     17850.0      2010-12     2010-12
9     13047.0      2010-12     2010-12

In [43]:
df[df['CustomerID'] == 13047][['CustomerID','InvoiceMonth','CohortMonth']]

        CustomerID InvoiceMonth CohortMonth
9          13047.0      2010-12     2010-12
10         13047.0      2010-12     2010-12
11         13047.0      2010-12     2010-12
12         13047.0      2010-12     2010-12
13         13047.0      2010-12     2010-12
...            ...          ...         ...
397488     13047.0      2011-10     2010-12
397489     13047.0      2011-10     2010-12
397490     13047.0      2011-10     2010-12
397491     13047.0      2011-10     2010-12
448287     13047.0      2011-11     2010-12

[172 rows x 3 columns]